from setuptools import setup
import sys
import os
import subprocess
from datetime import datetime
from PyQt5 import QtCore

APP = ['small_rss_reader.py']
DATA_FILES = [
    ('icons', [
        'icons/splash.png',
        'icons/rss_icon.png',
        'icons/rss_tray_icon.png',
        'icons/rss_icon.icns',
        'icons/movie_icon.png',
    ]),
]

# Locate Qt plugins (if needed)
qt_plugins_dir = os.path.join(QtCore.QLibraryInfo.location(QtCore.QLibraryInfo.PluginsPath))

def git_output(args):
    try:
        out = subprocess.check_output(["git", *args], cwd=os.path.dirname(__file__), text=True, timeout=2)
        return out.strip()
    except Exception:
        return ""

# Derive version info at build time
GIT_DESCRIBE = git_output(["describe", "--tags", "--dirty", "--always"]) or ""
GIT_TAG = git_output(["describe", "--tags", "--abbrev=0"]) or ""
GIT_COMMIT = git_output(["rev-parse", "--short", "HEAD"]) or ""
REMOTE_ORIGIN = git_output(["remote", "get-url", "origin"]) or "https://github.com/SergeyLavrentev/small-rss-reader"
BUILD_VERSION = GIT_DESCRIBE or (GIT_TAG and GIT_COMMIT and f"{GIT_TAG} ({GIT_COMMIT})") or (GIT_COMMIT or "")

# Write/overwrite app_version.py for runtime use
APP_VERSION_FILE = os.path.join(os.path.dirname(__file__), 'app_version.py')
try:
    with open(APP_VERSION_FILE, 'w') as f:
        f.write(
            "\n".join([
                '"""Autogenerated at build time. Do not edit manually."""',
                f'VERSION = {BUILD_VERSION!r}',
                f'TAG = {GIT_TAG!r}',
                f'COMMIT = {GIT_COMMIT!r}',
                f'ORIGIN = {REMOTE_ORIGIN!r}',
                "",
            ])
        )
except Exception:
    pass

OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'icons/rss_icon.icns',
    'packages': ['PyQt5'],
    'includes': [
        'PyQt5.QtWebEngineWidgets',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
    ],
    'excludes': ['packaging', 'python_dateutil'],
    'plist': {
        'CFBundleName': 'SmallRSSReader',
        'CFBundleIdentifier': 'com.rocker.SmallRSSReader',
        'CFBundleIconFile': 'rss_icon.icns',
        'LSUIElement': True,
    'CFBundleShortVersionString': BUILD_VERSION or '0.0.0',
    'CFBundleVersion': BUILD_VERSION or '0.0.0',
        'LSUIElement': False,  # Set to False so that the app appears in the Dock
        'NSPrincipalClass': 'NSApplication'
    },
    'verbose': True,
    'compressed': True,
    'strip': False,
}

setup(
    app=APP,
    name='SmallRSSReader',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
